### ISSUE TITLE
about the psnr for the real data

### ISSUE THREAD

**Issue by boxuLibrary** [SpectacularAI/3dgs-deblur#6]
Hi, it's an excellent work. I wonder how do you calculate the psnr for the real data, because we can not obtain the global shutter images from the same view of the rolling shutter images.

**Comment by oseiskar** [comment]
Great question! We use rolling shutter (and motion blur) compensation also for the evaluation cameras. As a result, our evaluation image renders do not aim to be sharp or global shutter equivalent.

In the first version of the paper, we used only the VIO-estimated velocities to compute the rolling shutter effect and motion blur for the evaluation images. In the latest version (published on arXiv today), we also optimize the evaluation image velocities. The evaluation image poses are also optimized in both versions (in a way that does not leak evaluation information into the Gaussians)
