### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by alphazhugit** [SpectacularAI/3dgs-deblur#9]
I found an "frames2" folder in the data of iPhone-lego, but my own data captured with Spectacular Rec App does not have it. How is this "frames2" folder generated?

**Comment by oseiskar** [comment]
Does your iPhone have a ToF sensor? ("LiDAR") The folder only exists in that case

**Comment by alphazhugit** [comment]
> Does your iPhone have a ToF sensor? ("LiDAR") The folder only exists in that case

Thank you very much for your explanation. I think I need a phone equipped with LiDAR.
